name: Update Sync Pipelineruns Repository List

on:
  push:
    # Only trigger on branches starting with rhoai-
    branches:
      - 'rhoai-*'
    # Only trigger if changes are made inside pipelineruns/
    paths:
      - 'pipelineruns/**'

permissions: write-all

env:
  WORKFLOW_FILE: ".github/workflows/sync-pipelineruns.yml"
  PIPELINERUNS_DIR: "pipelineruns"

jobs:
  sync-repository-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: red-hat-data-services
          repositories: konflux-central

      - name: Checkout code - main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout code - '${{ github.ref_name }}'
        uses: actions/checkout@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: ${{ github.ref_name }}


      - name: Print Debug Info
        run: |
          ls -lart
          ls -lart ${{ github.ref_name }}

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruyaml

      - name: Update repository list
        run: |
          python script/update-sync-pipelinerun-workflow-repository-list.py --workflow-file ${{ github.ref_name }}/${{ env.WORKFLOW_FILE }} --pipelinerun-dir ${{ github.ref_name }}/${{ env.PIPELINERUNS_DIR }}
  

      - name: Commit Changes
        run: |
          cd ${{ github.ref_name }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global color.ui always

          set -x
          git status
          git add ${{ env.WORKFLOW_FILE }}
          git diff --staged
          set +x

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
          echo "No changes to commit."
          else
          git commit -m "Updating repository list"
          fi

          
          git push origin ${{ github.ref_name }}

      # - name: Slack Notification
      #   if: ${{ failure() }}
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_MESSAGE: ':red-warning: Renovate Synchronization Failed for repo: ${{ matrix.config.repo }}!'
      #     SLACK_WEBHOOK: ${{ secrets.RHOAI_DEVOPS_SLACK_WEBHOOK }}
